### ISSUE TITLE
Need to review total received

### ISSUE THREAD

**Issue by 7h3v01c3** [Divicoin/diviscan-api#1]
By viewing this address you can see it is incorrectly  adding up the total received / sent occasionally. 

https://api.diviscan.io/address/DLDzAnAVjUHiu6JhDK9AzjHC7ForDZENNQ

This total includes the 12k and rewards each time.

Chainz shows
Received | 161,191.3875 DIVI | in 11 transactions
Sent | 161,191.3875 DIVI | in 11 transactions

Diviscan shows

balance_info |  
received | 16119138750000

However, the address only had a total of 16,933.7625

Which began as a UTXO with value of 12,373.7625  + 10 rewards of 456 DIVI each
then input of 16,933.7625 = ending is a 0 balance

**Comment by 99darwin** [comment]
Potentially the same issue fixed in 5e9e2c1ab471ef2cf0088ab90037a9c01152e9b0. Will review
